program SSBasico;

uses
  Forms,
  DB,
  DBTables,
  Dialogs,
  sysutils,
  UMenuP in 'UMenuP.pas' {fMenuP},
  UFornecedores in 'UFornecedores.pas' {fFornecedores},
  UMaterial in 'UMaterial.pas' {fMaterial},
  UOrdemCompra in 'UOrdemCompra.pas' {fOrdemCompra},
  UOrdemCompraCor in 'UOrdemCompraCor.pas' {fOrdemCompraCor},
  UProduto in 'UProduto.pas' {fProduto},
  URelMaterial in 'URelMaterial.pas' {fRelMaterial},
  UPrevMaterial in 'UPrevMaterial.pas' {fPrevMaterial},
  UPedido in 'UPedido.pas' {fPedido},
  UCliente in 'UCliente.pas' {fCliente},
  UPedidoMat in 'UPedidoMat.pas' {fPedidoMat},
  URelPedido in 'URelPedido.pas' {fRelPedido},
  UPrevRelClientes in 'UPrevRelClientes.pas' {fPrevRelClientes},
  URelClientes in 'URelClientes.pas' {fRelClientes},
  UPrevFornecedores in 'UPrevFornecedores.pas' {fPrevFornecedores},
  URelFornecedores in 'URelFornecedores.pas' {fRelFornecedores},
  UPrevVendedores in 'UPrevVendedores.pas' {fPrevVendedores},
  URelVendedores in 'URelVendedores.pas' {fRelVendedores},
  USetor in 'USetor.pas' {fSetor},
  UCopiaPedidos in 'UCopiaPedidos.pas' {fCopiaPedidos},
  UEmissaoNotaFiscal in 'UEmissaoNotaFiscal.pas' {fEmissaoNotaFiscal},
  UPrevContas in 'UPrevContas.pas' {fPrevContas},
  URelContas in 'URelContas.pas' {fRelContas},
  UBuscaPedido in 'UBuscaPedido.pas' {fBuscaPedido},
  UConsNotaFiscal in 'UConsNotaFiscal.pas' {fConsNotaFiscal},
  UNotaEntrada in 'UNotaEntrada.pas' {fNotaEntrada},
  UConsNotaEnt in 'UConsNotaEnt.pas' {fConsNotaEnt},
  URelNotaEntrada in 'URelNotaEntrada.pas' {fRelNotaEntrada},
  USobre in 'USobre.pas' {fSobre},
  URelPagForn in 'URelPagForn.pas' {fRelPagForn},
  URelPgtoJuros in 'URelPgtoJuros.pas' {fRelPgtoJuros},
  UPrevPgtoJuros in 'UPrevPgtoJuros.pas' {fPrevPgtoJuros},
  UPrevPagForn in 'UPrevPagForn.pas' {fPrevPagForn},
  UBaixaPedido in 'UBaixaPedido.pas' {fBaixaPedido},
  UConsPedido in 'UConsPedido.pas' {fConsPedido},
  UConsPedidoNota in 'UConsPedidoNota.pas' {fConsPedidoNota},
  UEtiqCliente in 'UEtiqCliente.pas' {fEtiqCliente},
  UEtiqFornecedor in 'UEtiqFornecedor.pas' {fEtiqFornecedor},
  UEtiqVendedor in 'UEtiqVendedor.pas' {fEtiqVendedor},
  ULancComissao in 'ULancComissao.pas' {fLancComissao},
  UNotaEntradaGrade in 'UNotaEntradaGrade.pas' {fNotaEntradaGrade},
  UOpcaoPedido in 'UOpcaoPedido.pas' {fOpcaoPedido},
  UParametros in 'UParametros.pas' {fParametros},
  UPrevNotasVendedor in 'UPrevNotasVendedor.pas' {fPrevNotasVendedor},
  UPrevPedidosNaoFat in 'UPrevPedidosNaoFat.pas' {fPrevPedidosNaoFat},
  UQuant in 'UQuant.pas' {fQuant},
  URegioes in 'URegioes.pas' {fRegioes},
  UUsuarios in 'UUsuarios.pas' {fUsuarios},
  ULogin in 'ULogin.pas' {fLogin},
  UAcesso in 'UAcesso.pas' {fAcesso},
  URelFichaTecnica in 'URelFichaTecnica.pas' {fRelFichaTecnica},
  UConsHistMat in 'UConsHistMat.pas' {fConsHistMat},
  UPrevMatMinimo in 'UPrevMatMinimo.pas' {fPrevMatMinimo},
  URelMatMinimo in 'URelMatMinimo.pas' {fRelMatMinimo},
  UConsEstoqueMat in 'UConsEstoqueMat.pas' {fConsEstoqueMat},
  UPrevRelHistMaterial in 'UPrevRelHistMaterial.pas' {fPrevRelHistMaterial},
  UOpcaoTalao in 'UOpcaoTalao.pas' {fOpcaoTalao},
  UMaoDeObra in 'UMaoDeObra.pas' {fMaoDeObra},
  UPedidoEsp in 'UPedidoEsp.pas' {fPedidoEsp},
  UConsPedidoEsp in 'UConsPedidoEsp.pas' {fConsPedidoEsp},
  UNotaFiscalGrade in 'UNotaFiscalGrade.pas' {fNotaFiscalGrade},
  UPrevNotaEntrada in 'UPrevNotaEntrada.pas' {fPrevNotaEntrada},
  UCopiaFornec in 'UCopiaFornec.pas' {fCopiaFornec},
  UConsOrdemCompra in 'UConsOrdemCompra.pas' {fConsOrdemCompra},
  UDctoEst in 'UDctoEst.pas' {fDctoEst},
  UPrevBalancoEst in 'UPrevBalancoEst.pas' {fPrevBalancoEst},
  UPrevRelOC in 'UPrevRelOC.pas' {fPrevRelOC},
  UProdutoConsumo in 'UProdutoConsumo.pas' {fProdutoConsumo},
  UFuncionario in 'UFuncionario.pas' {fFuncionario},
  URelTalao in 'URelTalao.pas' {fRelTalao},
  UPrevEmbDiario in 'UPrevEmbDiario.pas' {fPrevEmbDiario},
  URelEmbDiario in 'URelEmbDiario.pas' {fRelEmbDiario},
  UBaixaItPed in 'UBaixaItPed.pas' {fBaixaItPed},
  UBaixaItPedQtd in 'UBaixaItPedQtd.pas' {fBaixaItPedQtd},
  UPrevProgramacao in 'UPrevProgramacao.pas' {fPrevProgramacao},
  URelProgramacao in 'URelProgramacao.pas' {fRelProgramacao},
  UTabPreco in 'UTabPreco.pas' {fTabPreco},
  URelTabPreco in 'URelTabPreco.pas' {fRelTabPreco},
  UPrevContrFat in 'UPrevContrFat.pas' {fPrevContrFat},
  URelContrFat in 'URelContrFat.pas' {fRelContrFat},
  uRelCadCli in 'uRelCadCli.pas' {fRelCadCli},
  UConsAgeContato in 'UConsAgeContato.pas' {fConsAgeContato},
  URelPedidosNaoFat in 'URelPedidosNaoFat.pas' {fRelPedidosNaoFat},
  USenha in 'USenha.pas' {fSenha},
  URelFluxoFuturo in 'URelFluxoFuturo.pas' {fRelFluxoFuturo},
  UCheques in 'UCheques.pas' {fCheques},
  UChequeComp in 'UChequeComp.pas' {fChequeComp},
  UPrevCheque in 'UPrevCheque.pas' {fPrevCheque},
  URelCheque in 'URelCheque.pas' {fRelCheque},
  UDtReprog in 'UDtReprog.pas' {fDtReprog},
  UPrevContFornecedores in 'UPrevContFornecedores.pas' {fPrevContFornecedores},
  URelContFornecedores in 'URelContFornecedores.pas' {fRelContFornecedores},
  UEscNotaDevolPorItem in 'UEscNotaDevolPorItem.pas' {fEscNotaDevolPorItem},
  URelOrdemCompraMail in 'URelOrdemCompraMail.pas' {fRelOrdemCompraMail},
  UConsOrcamento in 'UConsOrcamento.pas' {fConsOrcamento},
  UOrcamento in 'UOrcamento.pas' {fOrcamento},
  URelEstoque in 'URelEstoque.pas' {fRelEstoque},
  UNotaFiscalOC in 'UNotaFiscalOC.pas' {fNotaFiscalOC},
  URelOrcamentoMail in 'URelOrcamentoMail.pas' {fRelOrcamentoMail},
  UNotaFiscalItens in 'UNotaFiscalItens.pas' {fNotaFiscalItens},
  UBaixaTalao in 'UBaixaTalao.pas' {fBaixaTalao},
  UConsVale in 'UConsVale.pas' {fConsVale},
  UBuscaVale in 'UBuscaVale.pas' {fBuscaVale},
  UHistCliente in 'UHistCliente.pas' {fHistCliente},
  UAprovaOrc in 'UAprovaOrc.pas' {fAprovaOrc},
  UPedidoItem in 'UPedidoItem.pas' {fPedidoItem},
  UConsEstUltMov in 'UConsEstUltMov.pas' {fConsEstUltMov},
  SelfPrintDefs in 'SelfPrintDefs.pas',
  SendMailOptions in 'SendMailOptions.pas' {FormSendMailOptions},
  UPrevPrevComissao in 'UPrevPrevComissao.pas' {fPrevPrevComissao},
  URelPrevComissao in 'URelPrevComissao.pas' {fRelPrevComissao},
  UPedidoItemCanc in 'UPedidoItemCanc.pas' {fPedidoItemCanc},
  UPrevProdutosFat in 'UPrevProdutosFat.pas' {fPrevProdutoFat},
  URelProdutosFat in 'URelProdutosFat.pas' {fRelProdutosFat},
  UConsHistCliente in 'UConsHistCliente.pas' {fConsHistCliente},
  uCopiaProdCli in 'uCopiaProdCli.pas' {fCopiaProdCli},
  UConsPedidoBR in 'UConsPedidoBR.pas' {fConsPedidoBR},
  USenhaAlt in 'USenhaAlt.pas' {fSenhaAlt},
  UNotaFiscalPed in 'UNotaFiscalPed.pas' {fNotaFiscalPed},
  UEscNotaDevolPorItem2 in 'UEscNotaDevolPorItem2.pas' {fEscNotaDevolPorItem2},
  UCopiaCliFornec in 'UCopiaCliFornec.pas' {fCopiaCliFornec},
  UConsTabPreco in 'UConsTabPreco.pas' {fConsTabPreco},
  UConsNotaBeneficiamento in 'UConsNotaBeneficiamento.pas' {fConsNotaBeneficiamento},
  URelNotaBeneficiamento in 'URelNotaBeneficiamento.pas' {fRelNotaBeneficiamento},
  UPrevPedCarteira in 'UPrevPedCarteira.pas' {fPrevPedCarteira},
  URelPedCarteira in 'URelPedCarteira.pas' {fRelPedCarteira},
  UNotaFiscalNDevolvida in 'UNotaFiscalNDevolvida.pas' {fNotaFiscalNDevolvida},
  UCopiaProdCliCor in 'UCopiaProdCliCor.pas' {fCopiaProdCliCor},
  URelContrFatAcumulado in 'URelContrFatAcumulado.pas' {fRelContrFatAcumulado},
  UConsPedCarteiraDet in 'UConsPedCarteiraDet.pas' {fConsPedCarteiraDet},
  UPrevPedCarteiraVlr in 'UPrevPedCarteiraVlr.pas' {fPrevPedCarteiraVlr},
  URelPedCarteiraVlr in 'URelPedCarteiraVlr.pas' {fRelPedCarteiraVlr},
  UPrevAcumuladoFat in 'UPrevAcumuladoFat.pas' {fPrevAcumuladoFat},
  URelAcumuladoFat in 'URelAcumuladoFat.pas' {fRelAcumuladoFat},
  UAltPrecoNotaFiscal in 'UAltPrecoNotaFiscal.pas' {fAltPrecoNotaFiscal},
  UEscNotaFiscalDevolPorItem2 in 'UEscNotaFiscalDevolPorItem2.pas' {fEscNotaFiscalDevolPorItem2},
  UConsNotaFiscalBeneficiamento in 'UConsNotaFiscalBeneficiamento.pas' {fConsNotaFiscalBeneficiamento},
  URelNotaFiscalBeneficiamento in 'URelNotaFiscalBeneficiamento.pas' {fRelNotaFiscalBeneficiamento},
  UConsProduto in 'UConsProduto.pas' {fConsProduto},
  URelPedidoBR2 in 'URelPedidoBR2.pas' {fRelPedidoBR2},
  URelProdutosPed in 'URelProdutosPed.pas' {fRelProdutosPed},
  URelProdutoPedDet in 'URelProdutoPedDet.pas' {fRelProdutosPedDet},
  UConsProdutoTam in 'UConsProdutoTam.pas' {fConsProdutoTam},
  UHistProduto in 'UHistProduto.pas' {fHistProduto},
  UHistProdutoDet in 'UHistProdutoDet.pas' {fHistProdutoDet},
  URelHistProdutosAcum in 'URelHistProdutosAcum.pas' {fRelHistProdutosAcum},
  UHistGeral in 'UHistGeral.pas' {fHistGeral},
  URelHistGeralCli in 'URelHistGeralCli.pas' {fRelHistGeralCli},
  URelHistGeralCliProd in 'URelHistGeralCliProd.pas' {fRelHistGeralCliProd},
  URelHistGeralCliMes in 'URelHistGeralCliMes.pas' {fRelHistGeralCliMes},
  URelHistGeralProd in 'URelHistGeralProd.pas' {fRelHistGeralProd},
  URelHistGeralCliProdCor in 'URelHistGeralCliProdCor.pas' {fRelHistGeralCliProdCor},
  URelHistGeralVend in 'URelHistGeralVend.pas' {fRelHistGeralVend},
  URelHistGeralProdMes in 'URelHistGeralProdMes.pas' {fRelHistGeralProdMes},
  URelHistGeralCliProdMes in 'URelHistGeralCliProdMes.pas' {fRelHistGeralCliProdMes},
  UConsClientesRef in 'UConsClientesRef.pas' {fConsClientesRef},
  URelClientesRef in 'URelClientesRef.pas' {fRelClientesRef},
  UFluxoFuturo in 'UFluxoFuturo.pas' {fFluxoFuturo},
  URelHistGeralCliProdMesRes in 'URelHistGeralCliProdMesRes.pas' {fRelHistGeralCliProdMesRes},
  UPrevPlanoContas2 in 'UPrevPlanoContas2.pas' {fPrevPlanoContas2},
  URelPlano2 in 'URelPlano2.pas' {fRelPlano2},
  UConsNotasPorPedido in 'UConsNotasPorPedido.pas' {fConsNotasPorPedido},
  UConsNotasPorPedidoGrade in 'UConsNotasPorPedidoGrade.pas' {fConsNotasPorPedidoGrade},
  URelNotasPorPedido in 'URelNotasPorPedido.pas' {fRelNotasPorPedido},
  UChequeCPagar in 'UChequeCPagar.pas' {fChequeCPagar},
  UBuscaDuplicata in 'UBuscaDuplicata.pas' {fBuscaDuplicata},
  UOrcamentoItens in 'UOrcamentoItens.pas' {fOrcamentoItens},
  UOrcamentoGrade in 'UOrcamentoGrade.pas' {fOrcamentoGrade},
  UGeraLote in 'UGeraLote.pas' {fGeraLote},
  UGeraLote2 in 'UGeraLote2.pas' {fGeraLote2},
  UConsLote in 'UConsLote.pas' {fConsLote},
  UDtReprogTalao in 'UDtReprogTalao.pas' {fDtReprogTalao},
  UCancelaLote in 'UCancelaLote.pas' {fCancelaLote},
  UBuscaTalao in 'UBuscaTalao.pas' {fBuscaTalao},
  URelTalao2 in 'URelTalao2.pas' {fRelTalao2},
  UConsPedPendFat in 'UConsPedPendFat.pas' {fConsPedPendFat},
  UConsPedidoPendLotes in 'UConsPedidoPendLotes.pas' {fConsPedidoPendLotes},
  rsDataSetError in '..\rslib\rsDataSetError.pas',
  UConsHistClienteProdCancelado in 'UConsHistClienteProdCancelado.pas' {fConsHistClienteProdCancelado},
  URelHistCliente in 'URelHistCliente.pas' {fRelHistCliente},
  ULoteQtd in 'ULoteQtd.pas' {fLoteQtd},
  UProdutoEdi in 'UProdutoEdi.pas' {fProdutoEDI},
  UConsMateriaPrimaPed in 'UConsMateriaPrimaPed.pas' {fConsMateriaPrimaPed},
  UConsMateriaPrima in 'UConsMateriaPrima.pas' {fConsMateriaPrima},
  URelMateriaPrima in 'URelMateriaPrima.pas' {fRelMateriaPrima},
  UCopiaProduto in 'UCopiaProduto.pas' {fCopiaProduto},
  UConsLoteMaisPesquisa in 'UConsLoteMaisPesquisa.pas' {fConsLoteMaisPesquisa},
  UConsMaterialFicha in 'UConsMaterialFicha.pas' {fConsMaterialFicha},
  URelOC in 'URelOC.pas' {fRelOC},
  UOrdemCompraCanc in 'UOrdemCompraCanc.pas' {fOrdemCompraCanc},
  UConsFornecedores in 'UConsFornecedores.pas' {fConsFornecedores},
  URelFornecedor2 in 'URelFornecedor2.pas' {fRelFornecedor2},
  UConsSaldos in 'UConsSaldos.pas' {fConsSaldos},
  URelMovimento in 'URelMovimento.pas' {fRelMovimento},
  UPrevEmbDiarioLote in 'UPrevEmbDiarioLote.pas' {fPrevEmbDiarioLote},
  URelEmbDiarioLote in 'URelEmbDiarioLote.pas' {fRelEmbDiarioLote},
  UPrevInventario in 'UPrevInventario.pas' {fPrevInventario},
  URelInventario in 'URelInventario.pas' {fRelInventario},
  UConsFaturamento in 'UConsFaturamento.pas' {fConsFaturamento},
  URelFaturamento in 'URelFaturamento.pas' {fRelFaturamento},
  UProdutoMat in 'UProdutoMat.pas' {fProdutoMat},
  UTipoProcesso in 'UTipoProcesso.pas' {fTipoProcesso},
  UConsPedido2 in 'UConsPedido2.pas' {fConsPedido2},
  URelPedidoProcesso in 'URelPedidoProcesso.pas' {fRelPedidoProcesso},
  URelLotes in 'URelLotes.pas' {fRelLotes},
  UConsMaterialParaFicha in 'UConsMaterialParaFicha.pas' {fConsMaterialParaFicha},
  UConsUltCompras in 'UConsUltCompras.pas' {fConsUltCompras},
  URelUltCompras in 'URelUltCompras.pas' {fRelUltCompras},
  UConvPrecoMaterial in 'UConvPrecoMaterial.pas' {fConvPrecoMaterial},
  UNotaFiscalCopia in 'UNotaFiscalCopia.pas' {fNotaFiscalCopia},
  UPrevNatOperacao in 'UPrevNatOperacao.pas' {fPrevNatOperacao},
  uRelNatOperacao in 'uRelNatOperacao.pas' {fRelNatOperacao},
  UConsFaturamentoGrupo in 'UConsFaturamentoGrupo.pas' {fConsFaturamentoGrupo},
  UTabPrecoMotivo in 'UTabPrecoMotivo.pas' {fTabPrecoMotivo},
  UTabPrecoHist in 'UTabPrecoHist.pas' {fTabPrecoHist},
  URelNotaBeneficiamentoAcumPed in 'URelNotaBeneficiamentoAcumPed.pas' {fRelNotaBeneficiamentoAcumPed},
  URelNotaBeneficiamentoAcum in 'URelNotaBeneficiamentoAcum.pas' {fRelNotaBeneficiamentoAcum},
  UAtualizaDtVencto2 in 'UAtualizaDtVencto2.pas' {fAtualizaDtVencto2},
  UConsFinanceiro in 'UConsFinanceiro.pas' {fConsFinanceiro},
  UPrevProduto in 'UPrevProduto.pas' {fPrevProduto},
  URelProdutoEst in 'URelProdutoEst.pas' {fRelProdutoEst},
  URelProduto in 'URelProduto.pas' {fRelProduto},
  UConsLimiteCredCliente in 'UConsLimiteCredCliente.pas' {fConsLimiteCredCliente},
  UConsHistCliente2 in 'UConsHistCliente2.pas' {fConsHistCliente2},
  URelFinanceiro in 'URelFinanceiro.pas' {fRelFinanceiro},
  UProdutoComb in 'UProdutoComb.pas' {fProdutoComb},
  UTipoIndicacao in 'UTipoIndicacao.pas' {fTipoIndicacao},
  UConsCliFornMov in 'UConsCliFornMov.pas' {fConsCliFornMov},
  URelCliFornMov in 'URelCliFornMov.pas' {fRelCliFornMov},
  UClienteRef in 'UClienteRef.pas' {fClienteRef},
  UConsNotaCancelada in 'UConsNotaCancelada.pas' {fConsNotaCancelada},
  UConsPagarReceber in 'UConsPagarReceber.pas' {fConsPagarReceber},
  UProdutoCombCopia in 'UProdutoCombCopia.pas' {fProdutoCombCopia},
  UVerificaContasRecPag in 'UVerificaContasRecPag.pas' {fVerificaContasRecPag},
  URelPagarReceber in 'URelPagarReceber.pas' {fRelPagarReceber},
  UNotaFiscalParcela in 'UNotaFiscalParcela.pas' {fNotaFiscalParcela},
  rsExcelExporta in '..\rslib\rsExcelExporta.pas',
  uConsLoteMateriais in 'uConsLoteMateriais.pas' {fConsLoteMateriais},
  UConsContasPagar in 'UConsContasPagar.pas' {fConsContasPagar},
  UCSTIPI in '..\generico\Manutencao\UCSTIPI.pas' {fCSTIPI},
  UPais in '..\generico\Manutencao\UPais.pas' {fPais},
  URelatorio in '..\generico\CReceber\URelatorio.pas' {fRelatorio},
  UConsCReceber in '..\generico\CReceber\UConsCReceber.pas' {fConsCReceber},
  UConsCReceberHist in '..\generico\CReceber\UConsCReceberHist.pas' {fConsCReceberHist},
  UConsCReceberRem in '..\generico\CReceber\UConsCReceberRem.pas' {fConsCReceberRem},
  UContasReceber2 in '..\generico\CReceber\UContasReceber2.pas' {fContasReceber2},
  UContasReceberDev in '..\generico\CReceber\UContasReceberDev.pas' {fContasReceberDev},
  UContasReceberPag in '..\generico\CReceber\UContasReceberPag.pas' {fContasReceberPag},
  UContasReceberPagSel in '..\generico\CReceber\UContasReceberPagSel.pas' {fContasReceberPagSel},
  UCopiaDuplicata in '..\generico\CReceber\UCopiaDuplicata.pas' {fCopiaDuplicata},
  ULancaCReceber in '..\generico\CReceber\ULancaCReceber.pas' {fLancaCReceber},
  ULancaCReceberItens in '..\generico\CReceber\ULancaCReceberItens.pas' {fLancaCReceberItens},
  UPrevCReceberSem in '..\generico\CReceber\UPrevCReceberSem.pas' {fPrevCReceberSem},
  UPrevDuplicatas in '..\generico\CReceber\UPrevDuplicatas.pas' {fPrevDuplicatas},
  UPrevRecCli in '..\generico\CReceber\UPrevRecCli.pas' {fPrevRecCli},
  URelRegDuplicatas in '..\generico\CReceber\URelRegDuplicatas.pas' {fRelRegDuplicatas},
  URelCopiaDupl in '..\generico\CReceber\URelCopiaDupl.pas' {fRelCopiaDupl},
  URelCReceber2 in '..\generico\CReceber\URelCReceber2.pas' {fRelCReceber2},
  URelCReceber3 in '..\generico\CReceber\URelCReceber3.pas' {fRelCReceber3},
  URelCReceberSem in '..\generico\CReceber\URelCReceberSem.pas' {fRelCReceberSem},
  URelRecCli in '..\generico\CReceber\URelRecCli.pas' {fRelRecCli},
  UUf in '..\generico\Manutencao\UUf.pas' {fUf},
  UCidade in '..\generico\Manutencao\UCidade.pas' {fCidade},
  UNotaFiscalAliq in '..\generico\faturamento\UNotaFiscalAliq.pas' {fNotaFiscalAliq},
  UNotaFiscalOutrasDespesas in '..\generico\faturamento\UNotaFiscalOutrasDespesas.pas' {fNotaFiscalOutrasDespesas},
  UNotaFiscalRef in '..\generico\faturamento\UNotaFiscalRef.pas' {fNotaFiscalRef},
  UNotaFiscalImp in '..\generico\faturamento\UNotaFiscalImp.pas' {fNotaFiscalImp},
  UDMNotaFiscal in 'UDMNotaFiscal.pas' {DMNotaFiscal: TDataModule},
  nfe_v110 in '..\generico\faturamento\nfe_v110.pas',
  uNFe in '..\generico\faturamento\uNFe.pas' {fNFe},
  UNotaFiscalConfirma in '..\generico\faturamento\UNotaFiscalConfirma.pas' {fNotaFiscalConfirma},
  URelDanfe in '..\generico\faturamento\URelDANFE.pas' {fRelDANFE},
  UNFeDados in 'UNFeDados.pas',
  UOutrosServicosNota in '..\generico\faturamento\UOutrosServicosNota.pas' {fOutrosServicosNota},
  URelProgramacaoRes2 in 'URelProgramacaoRes2.pas' {fRelProgramacaoRes2},
  SendMail in 'SendMail.pas',
  uClientesAusentes in 'uClientesAusentes.pas' {fClientesAusentes},
  uRelClientesAusentes in 'uRelClientesAusentes.pas' {fRelClientesAusentes},
  URelHistCliente2 in 'URelHistCliente2.pas' {fRelHistCliente2},
  UClienteConsHistorico in 'UClienteConsHistorico.pas' {fClienteConsHistorico},
  URelDuplicata in '..\generico\creceber\URelDuplicata.pas' {fRelDuplicata},
  UNotaFiscalCancelada in '..\generico\faturamento\UNotaFiscalCancelada.pas' {fNotaFiscalCancelada},
  UNotaFiscalOBS in '..\generico\faturamento\UNotaFiscalOBS.pas' {fNotaFiscalOBS},
  UEscFilial in '..\generico\Manutencao\UEscFilial.pas' {fEscFilial},
  UFilial in '..\generico\Manutencao\UFilial.pas' {fFilial},
  UConsLancCReceber in '..\generico\CReceber\UConsLancCReceber.pas' {fConsLancCReceber},
  UPrevNotasNatOpe2 in '..\generico\faturamento\UPrevNotasNatOpe2.pas' {fPrevNotasNatOpe2},
  URelNatNota2 in '..\generico\faturamento\URelNatNota2.pas' {fRelNatNota2},
  UAtividade in '..\generico\Manutencao\UAtividade.pas' {fAtividade},
  UAutorizacao in '..\generico\Manutencao\UAutorizacao.pas' {fAutorizacao},
  UClasFiscal in '..\generico\Manutencao\UClasFiscal.pas' {fClasFiscal},
  UCondPgto in '..\generico\Manutencao\UCondPgto.pas' {fCondPgto},
  UConsFornecAtiv in '..\generico\Manutencao\UConsFornecAtiv.pas' {fConsFornecAtiv},
  UCor in '..\generico\Manutencao\UCor.pas' {fCor},
  UEscImpressora in '..\generico\Manutencao\UEscImpressora.pas' {fEscImpressora},
  UFeriado in '..\generico\Manutencao\UFeriado.pas' {fFeriado},
  UObsAux in '..\generico\Manutencao\UObsAux.pas' {fObsAux},
  UPercSimples in '..\generico\faturamento\UPercSimples.pas' {fPercSimples},
  URelNotaCancelada in '..\generico\faturamento\URelNotaCancelada.pas' {fRelNotaCancelada},
  USitTributaria in '..\generico\Manutencao\USitTributaria.pas' {fSitTributaria},
  UTipoCobranca in '..\generico\CReceber\UTipoCobranca.pas' {fTipoCobranca},
  UUnidade in '..\generico\Manutencao\UUnidade.pas' {fUnidade},
  URelCReceberCliRed in '..\generico\CReceber\URelCReceberCliRed.pas' {fRelCReceberCliRed},
  UNotaFiscalCliTriang in 'UNotaFiscalCliTriang.pas' {fNotaFiscalCliTriang},
  UConsPedidoPend in 'UConsPedidoPend.pas' {fConsPedidoPend},
  URelPedidoPend in 'URelPedidoPend.pas' {fRelPedidoPend},
  UDMTabImposto in '..\generico\faturamento\UDMTabImposto.pas' {DMTabImposto: TDataModule},
  URegimeTrib in '..\generico\faturamento\URegimeTrib.pas' {fRegimeTrib},
  UTabCofins in '..\generico\faturamento\UTabCofins.pas' {fTabCofins},
  UTabPis in '..\generico\faturamento\UTabPis.pas' {fTabPis},
  USitTributariaSimples in '..\generico\manutencao\USitTributariaSimples.pas' {fSitTributariaSimples},
  UOrigemProd in '..\generico\faturamento\UOrigemProd.pas' {fOrigemProd},
  UNotaFiscalContingencia in '..\generico\faturamento\UNotaFiscalContingencia.pas' {fNotaFiscalContingencia},
  UNotaFiscalReboque in '..\generico\faturamento\UNotaFiscalReboque.pas' {fNotaFiscalReboque},
  UNotaFiscalLacre in '..\generico\faturamento\UNotaFiscalLacre.pas' {fNotaFiscalLacre},
  uNFeComandos in '..\generico\faturamento\uNFeComandos.pas',
  uNFeConsts in '..\NFe2.00\NFESrv\uNFeConsts.pas',
  UNFeInutilizacao in '..\generico\faturamento\UNFeInutilizacao.pas' {fNFeInutilizacao},
  UDMNFe in '..\generico\faturamento\UDMNFe.pas' {DMNFe: TDataModule},
  URelCReceberTipoCobrRed in '..\generico\creceber\URelCReceberTipoCobrRed.pas' {fRelCReceberTipoCobrRed},
  URelCReceberTipoCobr in '..\generico\creceber\URelCReceberTipoCobr.pas' {fRelCReceberTipoCobr},
  UNatOperacao in '..\generico\manutencao\UNatOperacao.pas' {fNatOperacao},
  URelPedidoProcesso2 in 'URelPedidoProcesso2.pas' {fRelPedidoProcesso2},
  uCalculos in '..\generico\faturamento\uCalculos.pas',
  UImpressora in '..\generico\manutencao\UImpressora.pas' {fImpressora},
  UInfDescontoNota in '..\generico\faturamento\UInfDescontoNota.pas' {fInfDescontoNota},
  UIndexador in '..\generico\faturamento\UIndexador.pas' {fIndexador},
  UImpostos in '..\generico\manutencao\UImpostos.pas' {fImpostos},
  UHistorico in '..\generico\manutencao\UHistorico.pas' {fHistorico},
  UGeraSintegra in '..\generico\faturamento\UGeraSintegra.pas' {fGeraSintegra},
  UJuros in '..\generico\financeiro\UJuros.pas' {fJuros},
  UMovimentos2 in '..\generico\financeiro\UMovimentos2.pas' {fMovimentos2},
  uMovimentosIns in '..\generico\financeiro\uMovimentosIns.pas' {fMovimentosIns},
  UEstPagamento in '..\generico\creceber\UEstPagamento.pas' {fEstPagamento},
  UCReceberAltera in '..\generico\creceber\UCReceberAltera.pas' {fCReceberAltera},
  UEmpresa in '..\generico\manutencao\UEmpresa.pas' {fEmpresa},
  UTransp in '..\generico\manutencao\UTransp.pas' {fTransp},
  UCopiaCli in '..\generico\manutencao\UCopiaCli.pas' {fCopiaCli},
  UAgendaTelef in '..\generico\manutencao\UAgendaTelef.pas' {fAgendaTelef},
  UAgeContato in '..\generico\manutencao\UAgeContato.pas' {fAgeContato},
  UAcessoAltSenha in '..\generico\manutencao\UAcessoAltSenha.pas' {fAcessoAltSenha},
  UBaixaItOC in '..\generico\Compras\UBaixaItOC.pas' {fBaixaItOC},
  UEntrExtOC in '..\generico\Compras\UEntrExtOC.pas' {fEntrExtOC},
  UBuscaOC in '..\generico\Compras\UBuscaOC.pas' {fBuscaOC},
  UCadastroSimples in '..\generico\manutencao\UCadastroSimples.pas' {fCadastroSimples},
  UConsCompras in '..\generico\Compras\UconsCompras.pas' {fConsCompras},
  URelCompras in '..\generico\Compras\URelCompras.pas' {fRelCompras},
  UConsDcto in '..\generico\Compras\UConsDcto.pas' {fConsDcto},
  UConsOCNotas in '..\generico\Compras\UConsOCNotas.pas' {fConsOCNotas},
  UContas in '..\generico\financeiro\UContas.pas' {fContas},
  UDctoGrade in '..\generico\Compras\UDctoGrade.pas' {fDctoGrade},
  UGrade in '..\generico\manutencao\UGrade.pas' {fGrade},
  UGrupoCliente in '..\generico\manutencao\UGrupoCliente.pas' {fGrupoCliente},
  UGrupos in '..\generico\manutencao\UGrupos.pas' {fGrupos},
  UVale in '..\generico\faturamento\UVale.pas' {fVale},
  UValeItens in '..\generico\faturamento\UValeItens.pas' {fValeItens},
  URelVale in '..\generico\faturamento\URelVale.pas' {fRelVale},
  URelVale2 in '..\generico\faturamento\URelVale2.pas' {fRelVale2},
  UConsCPagarHist in '..\generico\CPagar\UConsCPagarHist.pas' {fConsCPagarHist},
  UOutros in '..\generico\manutencao\UOutros.pas' {fOutros},
  UVendedor in '..\generico\Comissao\UVendedor.pas' {fVendedor},
  UConsComissao in '..\generico\Comissao\UConsComissao.pas' {fConsComissao},
  UConsComissaoDet in '..\generico\Comissao\UConsComissaoDet.pas' {fConsComissaoDet},
  UPgtoComissao2 in '..\generico\Comissao\UPgtoComissao2.pas' {fPgtoComissao2},
  UPermissoes in '..\generico\manutencao\UPermissoes.pas' {fPermissoes},
  UPedidoDesconto in '..\generico\PCP\UPedidoDesconto.pas' {fPedidoDesconto},
  UPedidoGrade in '..\generico\PCP\UPedidoGrade.pas' {fPedidoGrade},
  UPlanoContas in '..\generico\financeiro\UPlanoContas.pas' {fPlanoContas},
  UPrevVale in '..\generico\faturamento\UPrevVale.pas' {fPrevVale},
  URelExtComissao in '..\generico\Comissao\URelExtComissao.pas' {fRelExtComissao},
  UContasBoletoManual in '..\generico\financeiro\UContasBoletoManual.pas' {fContasBoletoManual},
  URelNatOper in '..\generico\manutencao\URelNatOper.pas' {fRelNatOper},
  ULancaCPagar in '..\generico\CPagar\ULancaCPagar.pas' {fLancaCPagar},
  UContasPagar2 in '..\generico\CPagar\UContasPagar2.pas' {fContasPagar2},
  UContasPagarDev in '..\generico\CPagar\UContasPagarDev.pas' {fContasPagarDev},
  UContasPagarPag in '..\generico\CPagar\UContasPagarPag.pas' {fContasPagarPag},
  UPrevCPagarSem in '..\generico\CPagar\UPrevCPagarSem.pas' {fPrevCPagarSem},
  UContasPagarPagSel in '..\generico\CPagar\UContasPagarPagSel.pas' {fContasPagarPagSel},
  UCPagarAltera in '..\generico\CPagar\UCPagarAltera.pas' {fCPagarAltera},
  URelCPagarSem in '..\generico\CPagar\URelCPagarSem.pas' {fRelCPagarSem},
  URelCPagar2 in '..\generico\CPagar\URelCPagar2.pas' {fRelCPagar2},
  URelCPagarPagto in '..\generico\CPagar\URelCPagarPagto.pas' {fRelCPagarPagto},
  UPrevDuplicatas2 in 'UPrevDuplicatas2.pas' {fPrevDuplicatas2},
  URelDuplicata2 in 'URelDuplicata2.pas' {fRelDuplicata2},
  uNotaFiscalAjustarIcms in '..\generico\faturamento\uNotaFiscalAjustarIcms.pas' {fNotaFiscalAjustarIcms},
  UConsLancCPagar in '..\generico\CPagar\UConsLancCPagar.pas' {fConsLancCPagar},
  UEstPagamentoPagar in '..\generico\CPagar\UEstPagamentoPagar.pas' {fEstPagamentoPagar},
  UMovimentosEnc in '..\generico\financeiro\UMovimentosEnc.pas' {fMovimentosEnc},
  UConsMovFinanceiro in '..\generico\financeiro\UConsMovFinanceiro.pas' {fConsMovFinanceiro},
  UDMMaterialFornecedor in '..\generico\Compras\UDMMaterialFornecedor.pas' {DMMaterialFornecedor: TDataModule},
  uMaterialFornecedor in '..\generico\Compras\uMaterialFornecedor.pas' {fMaterialFornecedor},
  UCBarra in '..\generico\manutencao\UCBarra.pas' {fCBarra},
  UConsPlanoContasCad in '..\generico\financeiro\UConsPlanoContasCad.pas' {fConsPlanoContasCad},
  URelPlanoContasCad in '..\generico\financeiro\URelPlanoContasCad.pas' {fRelPlanoContasCad},
  UPrevNotasEnt in '..\generico\Compras\UPrevNotasEnt.pas' {fPrevNotasEnt},
  UPrevNComprasNatOpe in '..\generico\Compras\UPrevNComprasNatOpe.pas' {fPrevNComprasNatOpe},
  URelNotasEnt in '..\generico\Compras\URelNotasEnt.pas' {fRelNotasEnt},
  URelNComprasNatOpe in '..\generico\Compras\URelNComprasNatOpe.pas' {fRelNComprasNatOpe},
  UNotaFiscalNumNota in '..\generico\faturamento\UNotaFiscalNumNota.pas' {fNotaFiscalNumNota},
  UConsProduto2 in 'UConsProduto2.pas' {fConsProduto2},
  uRelConsProduto in 'uRelConsProduto.pas' {fRelConsProduto},
  uRelConsProdutoGrupo in 'uRelConsProdutoGrupo.pas' {fRelConsProdutoGrupo},
  URelProdutoEtiq in 'URelProdutoEtiq.pas' {fRelProdutoEtiq},
  UNotaEntradaQtd in 'UNotaEntradaQtd.pas' {fNotaEntradaQtd},
  UCReceberAlteraSel in '..\generico\creceber\UCReceberAlteraSel.pas' {fCReceberAlteraSel},
  DmdDatabase in 'FB\DmdDatabase.pas' {dmDatabase: TDataModule},
  UDMCobEletronica in '..\generico\CobEletronica\UDMCobEletronica.pas' {DMCobEletronica: TDataModule},
  UCobEletronicaC in '..\generico\CobEletronica\UCobEletronicaC.pas' {fCobEletronicaC},
  UCobEletronica in '..\generico\CobEletronica\UCobEletronica.pas' {fCobEletronica},
  UCobEletronicaBusca in '..\generico\CobEletronica\UCobEletronicaBusca.pas' {fCobEletronicaBusca},
  UArqRetornoBrasil in '..\generico\CobEletronica\UArqRetornoBrasil.pas' {fArqRetornoBrasil},
  UBcoBrasil in '..\generico\CobEletronica\UBcoBrasil.pas' {fBcoBrasil},
  UEnviarBanco in '..\generico\CobEletronica\UEnviarBanco.pas' {fEnviarBanco},
  URelArqRetBrasil in '..\generico\CobEletronica\URelArqRetBrasil.pas' {fRelArqRetBrasil},
  URelArqRetBrasilRed in '..\generico\CobEletronica\URelArqRetBrasilRed.pas' {fRelArqRetBrasilRed},
  URelCobEletronica in '..\generico\CobEletronica\URelCobEletronica.pas' {fRelCobEletronica},
  uUtilBanco in '..\generico\CobEletronica\uUtilBanco.pas',
  dmdCadCliente in 'FB\dmdCadCliente.pas' {dmCadCliente: TDataModule},
  uIntegracao in 'FB\uIntegracao.pas',
  arTypes in '..\rslib\arTypes.pas',
  UBcoItau in '..\generico\CobEletronica\UBcoItau.pas' {fBcoItau},
  UCobItau in '..\generico\CobEletronica\UCobItau.pas' {fCobItau},
  UCobBrasil in '..\generico\CobEletronica\UCobBrasil.pas' {fCobBrasil},
  UCobItauAlt in '..\generico\CobEletronica\UCobItauAlt.pas' {fCobItauAlt},
  UCobBrasilAlt in '..\generico\CobEletronica\UCobBrasilAlt.pas' {fCobBrasilAlt},
  UArqRetornoItau in '..\generico\CobEletronica\UArqRetornoItau.pas' {fArqRetornoItau},
  URelArqRetItau in '..\generico\CobEletronica\URelArqRetItau.pas' {fRelArqRetItau},
  UDMBanco in '..\generico\CobEletronica\UDMBanco.pas' {DMBanco: TDataModule},
  uRelBoletoItau in '..\generico\CobEletronica\uRelBoletoItau.pas' {fRelBoletoItau},
  UCobrancaEletronica in '..\generico\CobEletronica\UCobrancaEletronica.pas' {fCobrancaEletronica},
  URelCobrancaEletronica in '..\generico\CobEletronica\URelCobrancaEletronica.pas' {fRelCobrancaEletronica},
  uUtilPadrao in '..\generico\util\uUtilPadrao.pas',
  UDMCupom in '..\generico\faturamento\UDMCupom.pas' {DMCupom: TDataModule},
  UDMSitTrib_CF in '..\generico\faturamento\UDMSitTrib_CF.pas' {DMSitTrib_CF: TDataModule},
  UCupomFiscal in '..\generico\faturamento\UCupomFiscal.pas' {fCupomFiscal},
  uUtilCupomFiscal in '..\generico\faturamento\uUtilCupomFiscal.pas',
  UCupomFiscalC in '..\generico\faturamento\UCupomFiscalC.pas' {fCupomFiscalC},
  dmdCadProduto in 'FB\dmdCadProduto.pas' {dmCadProduto: TDataModule},
  UCupomFiscalCli in '..\generico\faturamento\UCupomFiscalCli.pas' {fCupomFiscalCli},
  UCupomFiscalPgto in '..\generico\faturamento\UCupomFiscalPgto.pas' {fCupomFiscalPgto},
  UCupomFiscalCanc in '..\generico\faturamento\UCupomFiscalCanc.pas' {fCupomFiscalCanc},
  UCupomFiscalOpcoes in '..\generico\faturamento\UCupomFiscalOpcoes.pas' {fCupomFiscalOpcoes},
  uImpFiscal_Daruma in '..\generico\faturamento\uImpFiscal_Daruma.pas',
  UDaruma_iMFLerSerial_ECF in '..\generico\faturamento\UDaruma_iMFLerSerial_ECF.pas' {fDaruma_iMFLerSerial_ECF},
  UDaruma_iMFLer_ECF in '..\generico\faturamento\UDaruma_iMFLer_ECF.pas' {fDaruma_iMFLer_ECF},
  UClienteTerceiroC in 'FB\UClienteTerceiroC.pas' {fClienteTerceiroC},
  UClienteTerceiro in 'FB\UClienteTerceiro.pas' {fClienteTerceiro},
  UNotaFiscalClienteTerc in 'UNotaFiscalClienteTerc.pas' {fNotaFiscalClienteTerc},
  UDMClienteTerceiro in 'FB\UDMClienteTerceiro.pas' {DMClienteTerceiro: TDataModule},
  uDmProdutoCarto in '..\generico\manutencao\uDmProdutoCarto.pas' {dmProdutoCarto: TDataModule},
  uProdutoCartoC in '..\generico\manutencao\uProdutoCartoC.pas' {fProdutoCartoC},
  uProdutoCarto in '..\generico\manutencao\uProdutoCarto.pas' {fProdutoCarto},
  uProdutoCartoCor in '..\generico\manutencao\uProdutoCartoCor.pas' {fProdutoCartoCor},
  UConsCliente in 'UConsCliente.pas' {fConsCliente},
  URelClientes3 in 'URelClientes3.pas' {fRelClientes3},
  UDMPedAmostra in 'FB\UDMPedAmostra.pas' {DMPedAmostra: TDataModule},
  UPedAmostra in 'FB\UPedAmostra.pas' {fPedAmostra},
  UPedAmostraItem in 'FB\UPedAmostraItem.pas' {fPedAmostraItem},
  uProdutoCartoR in '..\generico\manutencao\uProdutoCartoR.pas' {fProdutoCartoR},
  URelFaturamentoProd in 'URelFaturamentoProd.pas' {fRelFaturamentoProd},
  UConsAmostra in 'UConsAmostra.pas' {fConsAmostra},
  URelPedAmostra in 'URelPedAmostra.pas' {fRelPedAmostra},
  UDMMovPedido in 'FB\UDMMovPedido.pas' {DMMovPedido: TDataModule},
  dmdCadSetor in 'FB\dmdCadSetor.pas' {dmCadSetor: TDataModule},
  UConsMovPedido in 'FB\UConsMovPedido.pas' {fConsMovPedido},
  UInfFabrica in 'UInfFabrica.pas' {fInfFabrica},
  ULancaCPagarItens in '..\generico\CPagar\ULancaCPagarItens.pas' {fLancaCPagarItens},
  URelCPagarPlano in '..\generico\CPagar\URelCPagarPlano.pas' {fRelCPagarPlano},
  URelReciboRec2 in 'URelReciboRec2.pas' {fRelReciboRec2},
  UPosicao in '..\generico\PCP\UPosicao.pas' {fPosicao},
  UProdutoPosicao in 'UProdutoPosicao.pas' {fProdutoPosicao},
  UConvProduto in 'UConvProduto.pas' {fConvProduto},
  uFacaC in '..\generico\manutencao\uFacaC.pas' {fFacaC},
  UDMCarteira in '..\generico\CobEletronica\UDMCarteira.pas' {DMCarteira: TDataModule},
  UCarteiraC in '..\generico\CobEletronica\UCarteiraC.pas' {fCarteiraC},
  UCarteira in '..\generico\CobEletronica\UCarteira.pas' {fCarteira},
  UBancoCNAB in '..\generico\CobEletronica\UBancoCNAB.pas' {fBancoCNAB},
  UDMBanco_CNAB in '..\generico\CobEletronica\UDMBanco_CNAB.pas' {DMBanco_CNAB: TDataModule},
  UDMCentroCusto in '..\generico\financeiro\UDMCentroCusto.pas' {DMCentroCusto: TDataModule},
  UCentroCusto in '..\generico\financeiro\UCentroCusto.pas' {fCentroCusto},
  uConvCPagar in 'uConvCPagar.pas' {fConvCPagar},
  UConsPlanoContas in '..\generico\financeiro\UConsPlanoContas.pas' {fConsPlanoContas},
  URelPlanoContas in '..\generico\financeiro\URelPlanoContas.pas' {fRelPlanoContas},
  UDMTipo_Produto in 'FB\UDMTipo_Produto.pas' {DMTipo_Produto: TDataModule},
  UTipo_ProdutoC in 'FB\UTipo_ProdutoC.pas' {fTipo_ProdutoC},
  UTipo_Produto in 'FB\UTipo_Produto.pas' {fTipo_Produto},
  UReferenciaInf in 'UReferenciaInf.pas' {fReferenciaInf},
  UDMMatriz_Loc in 'FB\UDMMatriz_Loc.pas' {DMMatriz_Loc: TDataModule},
  UMatriz_LocC in 'FB\UMatriz_LocC.pas' {fMatriz_LocC},
  UMatriz_Loc in 'FB\UMatriz_Loc.pas' {fMatriz_Loc},
  UDMAgenda in 'FB\UDMAgenda.pas' {DMAgenda: TDataModule},
  UAgenda in 'FB\UAgenda.pas' {fAgenda},
  UAgendaDig in 'FB\UAgendaDig.pas' {fAgendaDig},
  UConsAgenda in 'FB\UConsAgenda.pas' {fConsAgenda},
  dmdCadFuncionario in 'FB\dmdCadFuncionario.pas' {dmCadFuncionario: TDataModule},
  UReagendamento in 'FB\UReagendamento.pas' {fReagendamento},
  UProdutoFerramental in 'FB\UProdutoFerramental.pas' {fProdutoFerramental},
  UDMProcesso in 'FB\UDMProcesso.pas' {DMProcesso: TDataModule},
  UProdutoTempo in 'FB\UProdutoTempo.pas' {fProdutoTempo},
  rsDBUtils in '..\rslib\rsDBUtils.pas',
  UProcessoC in 'FB\UProcessoC.pas' {fProcessoC},
  UProcesso in 'FB\UProcesso.pas' {fProcesso},
  URelFichaTecnicaMet in 'URelFichaTecnicaMet.pas' {fRelFichaTecnicaMet},
  uFacaItem in '..\generico\manutencao\uFacaItem.pas' {fFacaItem},
  uFaca in '..\generico\manutencao\uFaca.pas' {fFaca},
  uUtilVar in '..\generico\util\uUtilVar.pas',
  UDMEstoque in 'FB\UDMEstoque.pas' {DMEstoque: TDataModule},
  UDMTalao in 'FB\UDMTalao.pas' {DMTalao: TDataModule},
  UGeraLoteFB in 'FB\UGeraLoteFB.pas' {fGeraLoteFB},
  UConsLoteFB in 'FB\UConsLoteFB.pas' {fConsLoteFB},
  URelTalaoFB in 'FB\URelTalaoFB.pas' {fRelTalaoFB},
  UCobEletronicaImp in '..\generico\CobEletronica\UCobEletronicaImp.pas' {fCobEletronicaImp},
  UDMNFeFB in '..\generico\faturamento\UDMNFeFB.pas' {DMNFeFB: TDataModule},
  UNotaFiscalCCe in '..\generico\faturamento\UNotaFiscalCCe.pas' {fNotaFiscalCCe},
  UNotaFiscalCCeDet in '..\generico\faturamento\UNotaFiscalCCeDet.pas' {fNotaFiscalCCeDet},
  URelCCe in '..\generico\faturamento\URelCCe.pas' {fRelCCe},
  UNFeEmailC in '..\generico\faturamento\UNFeEmailC.pas' {fNFeEmailC},
  UNFeEmail in '..\generico\faturamento\UNFeEmail.pas' {fNFeEmail},
  uRelPedido3 in 'URelPedido3.pas' {fRelPedido3},
  UConsMovPedido2 in 'FB\UConsMovPedido2.pas' {fConsMovPedido2},
  UMovPedido_Nota in 'FB\UMovPedido_Nota.pas' {fMovPedido_Nota},
  UDM1 in 'UDM1.pas' {DM1: TDataModule},
  UDM2 in 'UDM2.pas' {DM2: TDataModule},
  dmdCadVendedor in '..\generico\Comissao\FB\dmdCadVendedor.pas' {dmCadVendedor: TDataModule},
  dmdCadCor in '..\generico\manutencao\FB\dmdCadCor.pas' {dmCadCor: TDataModule},
  dmdCadPosicao in '..\generico\PCP\FB\dmdCadPosicao.pas' {dmCadPosicao: TDataModule},
  dmdCadGrupo in '..\generico\manutencao\FB\dmdCadGrupo.pas' {dmCadGrupo: TDataModule},
  UDMVendedorMeta in '..\generico\Comissao\FB\UDMVendedorMeta.pas' {DMVendedorMeta: TDataModule},
  UVendedorMetaC in '..\generico\Comissao\FB\UVendedorMetaC.pas' {fVendedorMetaC},
  UVendedorMeta in '..\generico\Comissao\FB\UVendedorMeta.pas' {fVendedorMeta},
  uDmAux in 'uDmAux.pas' {DmAux: TDataModule},
  UHistPedido in 'UHistPedido.pas' {fHistPedido},
  UConsCBarra in '..\generico\manutencao\UConsCBarra.pas' {fConsCBarra},
  URelCBarra in '..\generico\manutencao\URelCBarra.pas' {fRelCBarra},
  URelHistPedido in 'URelHistPedido.pas' {fRelHistPedido},
  UEtiqCx in 'UEtiqCx.pas' {fEtiqCx},
  URelEtiqCx in 'URelEtiqCx.pas' {fRelEtiqCx},
  UEtiqRotulo in 'UEtiqRotulo.pas' {fEtiqRotulo},
  URelEtiqRotulo2 in 'URelEtiqRotulo2.pas' {fRelEtiqRotulo2},
  UConsMovAux in '..\generico\financeiro\UConsMovAux.pas' {fConsMovAux},
  URelEtiqCx2 in 'URelEtiqCx2.pas' {fRelEtiqCx2},
  UConsPedidoBRTam in 'UConsPedidoBRTam.pas' {fConsPedidoBRTam},
  UEtiquetaCaixaInd in 'UEtiquetaCaixaInd.pas' {fEtiquetaCaixaInd},
  UBcoCaixa in '..\generico\cobeletronica\UBcoCaixa.pas' {fBcoCaixa},
  uUtil_NFe in '..\generico\faturamento\uUtil_NFe.pas',
  UDMTabIBPT in '..\generico\faturamento\UDMTabIBPT.pas' {DMTabIBPT: TDataModule},
  UTabIBPTC in '..\generico\faturamento\UTabIBPTC.pas' {fTabIBPTC},
  UTabIBPT in '..\generico\faturamento\UTabIBPT.pas' {fTabIBPT};

{$R *.RES}

begin
  try
  Application.Initialize;
  Session.AddPassword('46w3zq');
  Application.Title := 'SSBásico';
  Application.CreateForm(TDM1, DM1);
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(TdmDatabase, dmDatabase);
  Application.CreateForm(TfMenuP, fMenuP);
  Application.Run;
  except
    on e: Exception do
      ShowMessage('Ocorreu o seguinte erro ao executar: ' + #13 + e.Message);
  end;
end.
